apiVersion: v1
kind: Service
metadata:
  name: {{ include "motion-chart.fullname" . }}
  labels:
    {{- include "motion-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (index .Values.service "nodePort") }}
      nodePort: {{ index .Values.service "nodePort" }}
      {{- end }}
  selector:
    {{- include "motion-chart.selectorLabels" . | nindent 4 }}
